<div class="container">
    <div class="panel panel-default">
        <div class="panel-heading">
                    <h3 class="panel-title"><span class="btn btn-info btn-sm disabled">
                       Modifica &nbsp; <?php echo $this->pageInfo->pageType; ?>
                </span>
                </h3>
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-md-12">
              <?php echo $this->form; ?>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript" src="/ress/js/tinymce/tinymce.min.js"></script>
<script type="text/javascript">
tinymce.init({
    selector: "#pageContent",
    plugins: [
        "advlist autolink lists link image charmap print preview anchor",
        "searchreplace visualblocks code fullscreen",
        "insertdatetime media table contextmenu paste"
    ],
    toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image"
});
</script>