<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title><?php //echo $this->setMeta(); ?></title>

    <!-- Bootstrap core CSS -->
    <link href="/ress/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/ress/css/dashboard.css" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    
    <script src="/ress/js/jquery-ui-1.11.1.custom/jquery-ui.min.js"></script>
    <link href="/ress/js/jquery-ui-1.11.1.custom/jquery-ui.min.css" rel="stylesheet">
    
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="navbar navbar-inverse navbar-static-top" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Will.ro</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="/admin/dashboard">Dashboard</a></li>
            <li><a href="<?php echo $this->url(array(), 'allLinks'); ?>">Links</a></li>
            <li><a href="/admin/promo-links">Linkuri sponsorizate</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Settings <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="/admin/advertising">Advertising</a></li>
                <li><a href="/admin/users">Users</a></li>
                <li class="divider"></li>
                <li><a href="/admin/category">Categories</a></li>
                <li><a href="/admin/modules">Modules</a></li>
                <li><a href="/admin/pages">Pages</a></li>
              </ul>
            </li>
            <li><a href="/admin/logout">Logout</a></li>
          </ul>
        </div>
      </div>
    </div>
      
    
      
<?php echo $this->layout()->content; ?>
     
     
  
    
    <script src="/ress/js/bootstrap.min.js"></script>
    <script type='text/javascript'>
     $(document).ready(function(){
	$("body").tooltip({
		selector: '[data-toggle=tooltip]',
		placement : 'top'
	});
	$("body").tooltip({
		selector: '[data-toggle=tooltip]',
		placement : 'right'
	});
	$("body").tooltip({
		selector: '[data-toggle=tooltip]',
		placement : 'bottom'
	});
	$("body").tooltip({
		selector: '[data-toggle=tooltip]',
		placement : 'left'
	});
    });
  </script>
  
 
  
  </body>
</html> 