<div class="container">
    <div class="panel panel-default">
        <div class="panel-heading">
            <div class="panel-title">
                <span class="btn btn-info btn-sm disabled">
                    Modifica - <?php echo $this->catInfo->category; ?>
                </span>
            </div>
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-xs-6">
              <?php echo $this->form; ?>
                </div>
            </div>
        </div>
    </div>
</div>
