<div class="container">
    <div class="panel panel-default">
        <div class="panel-heading">
                    <h3 class="panel-title"><span class="btn btn-info btn-sm disabled">
                            Trebuie aprobat &nbsp; 
                <span class="badge">
                    <?php echo count($this->listObj); ?>
                </span>
                </span></h3>
        </div>
        <div class="panel-body">
              <div class="list-group">
                <?php foreach ($this->listObj as $links) : ?>
                  <li class="list-group-item">
                    <h4 class="list-group-item-heading">
                        <a href="<?php echo $this->url(array('linkId' => $links->id), 'viewLink'); ?>">
                            <?php echo $links->title; ?>
                            </a>
                        <span class="label label-info pull-right">
                            <?php echo $links->type; ?>
                        </span></h4>
                    <p class="list-group-item-text">
                        <small><?php echo $links->url; ?> &nbsp; 
                        </small>
                        <a href="<?php echo $this->url(array('linkId' => $links->id), 'editLink'); ?>"><i class="glyphicon glyphicon-pencil text-info"></i></a> &nbsp; 
                        <a href="<?php echo $this->url(array('linkId' => $links->id), 'delLink'); ?>" onclick="return( confirm('Esti sigur ca vrei sa stergi acest link?'))">
                            <i class="glyphicon glyphicon glyphicon-remove text-danger"></i></a> &nbsp; 
                            <span class="text-muted" data-toggle="tooltip" data-placement="right" data-original-title="<?php echo ' e-Mail:'.$links->email.' IP:'.$links->ip; ?>">
                                <i class="glyphicon glyphicon-info-sign"></i>  &nbsp; 
                            </span>
                         
                    <br /><?php echo substr($links->shortDescription, 0, 150).'..'; ?></p>
                  </li>
                <?php endforeach; ?>
              </div>
        </div>
    </div>
</div>
