<div class="container">
    <?php echo $this->render('flash-messenger.phtml'); ?>
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">
                <span class="btn btn-info btn-sm disabled">Adauga reclama</span>
            </h3>
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-xs-6">
              <?php echo $this->form; ?>
                </div>
            </div>
        </div>
    </div>
</div>
