<div class="container">
     <?php echo $this->render('flash-messenger.phtml'); ?>
    <div class="panel panel-default">
        <div class="panel-heading">
            <div class="panel-title"><span class="btn btn-info btn-sm disabled">Reclame &nbsp; 
                <span class="badge">
                    <?php echo count($this->advL); ?>
                </span></span> &nbsp; 
                <a href="<?php echo $this->url(array(
                    'module' => 'admin',
                    'controller' => 'advertising',
                    'action' => 'add-advertising'
                        ),
                        'default'); ?>">
                    <button type="button" class="btn btn-primary btn-sm">Adauga o reclama</button></a>
            </div>
                
        </div>
        <div class="panel-body">
            <div class="table-responsive">
                <table class="table table-hover"> <?php foreach ($this->advL as $adv) : ?>
                    <tr>
                        <td style="width: 15px;">
                            <a href="<?php echo $this->url(array('id' => $adv->id), 'editAdvertising'); ?>">Editeaza</a>
                        </td> 
                        <td style="width: 155px;">
                            <a href="<?php echo $this->url(array('id' => $adv->id), 'delAdvertising'); ?>" onclick="return(confirm('esti sigura'))">Sterge</a> &nbsp; 
                        <span class="label label-info"><?php echo htmlspecialchars($adv->layout); ?></span></td> 
                        <td><?php echo $adv->title; ?></td> 
                        <td><?php // echo htmlspecialchars($adv->adv_code); ?></td> 
                    </tr>
                <?php endforeach; ?>
                </table>
            </div>
        </div>
    </div>
</div>
